version: 1.0.{build}
branches:
  only:
  - master
  - develop
skip_branch_with_pr: true
image:
- Ubuntu1804
- macOS-Mojave
init:
- sh: mkdir  $HOME/projects/qmakebin
environment:
  QTBRANCH: 5.15
install:
- sh: git clone -b $QTBRANCH https://github.com/qt/qtbase.git $HOME/projects/qtbase
build_script:
- sh: >-
    cd $HOME/projects/qtbase && ./configure -opensource -confirm-license -no-opengl && cd -

    cp -r $HOME/projects/qtbase/bin $HOME/projects/qmakebin/

    cp -r $HOME/projects/qtbase/mkspecs $HOME/projects/qmakebin/

    cd $HOME/projects && tar -zcvf qmakebin.tgz qmakebin && cd -

    cd $HOME/projects && zip builddefs-qmake-package.zip -r builddefs-qmake && cd -

    mv $HOME/projects/qmakebin.tgz $APPVEYOR_BUILD_FOLDER

    mv $HOME/projects/builddefs-qmake-latest.zip $APPVEYOR_BUILD_FOLDER
artifacts:
- path: qmakebin.tgz
  name: qmakebin
- path: builddefs-qmake-package.zip
  name: builddefs-qmake-package
deploy:
- provider: GitHub
  release: ${APPVEYOR_BUILD_WORKER_IMAGE}/qmake-latest
  auth_token:
    secure: WUZuOKLtErzvGojYwISnWio7doATSkiTNVWQaO1iz9ozEJQDPMIQKbF4Hzn8SkLU
  artifact: qmakebin
  on:
    APPVEYOR_REPO_TAG: true
- provider: GitHub
  release: builddefs-qmake-${APPVEYOR_REPO_TAG_NAME}
  auth_token:
    secure: WUZuOKLtErzvGojYwISnWio7doATSkiTNVWQaO1iz9ozEJQDPMIQKbF4Hzn8SkLU
  artifact: builddefs-qmake-package
  on:
    APPVEYOR_REPO_TAG: true
- provider: GitHub
  release: builddefs-qmake-latest
  auth_token:
    secure: WUZuOKLtErzvGojYwISnWio7doATSkiTNVWQaO1iz9ozEJQDPMIQKbF4Hzn8SkLU
  artifact: builddefs-qmake-package
  on:
    branch: develop